### ISSUE TITLE
Could you please tell us about the release date of the full version?

### ISSUE THREAD

**Issue by nessessence** [JeremyXSC/FineGPR#2]
Hi,
I'm really interested in your work and looking forward to it. 
Could you please tell us about the release date of the full version? The tentative schedule is fine. 

// Thanks for sharing this interesting work to the community.

**Comment by JeremyXSC** [comment]
Thanks for your interest in our work. For your questions, we will try our best to release the whole dataset as soon as possible when we complete whole project with other cooperators. The current tentative schedule is early next year. Thanks a lot!
