### ISSUE TITLE
Keypoint location annotation file

### ISSUE THREAD

**Issue by YoungGenuineLee** [JeremyXSC/FineGPR#6]
Hello.
Thank you for providing such a great dataset!
I found out that you can receive a human body mask and keypoint location annotation through "Extendibility" in the README.md file.
I've referenced Git and Paper, but I haven't checked the downloadable link. Is there any way I can get annotation file? Thank you.

**Comment by JeremyXSC** [comment]
Thanks for your interests in our work. The downloadable links of human body mask and keypoint location annotation are in the project page. Hoping this work can bring some merits to your research. Thank you!

**Comment by YoungGenuineLee** [comment]
Thanks to you, I found it!
Thank you so much for creating valuable data!
